name: Push Image to ECR

on: [push]

permissions:
  contents: read

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Push to ECR and Write Summary
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: d1i4x5x9
        REPOSITORY: python-web-server
        IMAGE_TAG: ${{ github.sha }}
        GALLERY: gallery.ecr.aws
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        # Write Summary
        cat >> "$GITHUB_STEP_SUMMARY" << EOF
        ## Image Details
        | Container Registry | Image |
        | ------------------ |-------|
        | [XYZ Entreprises](https://$GALLERY/$REGISTRY_ALIAS) | [$REGISTRY/$REGISTRY_ALIAS/$REPOSITORY](https://$GALLERY/$REGISTRY_ALIAS/$REPOSITORY) |
        EOF
